apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: repositoryservice
  name: repositoryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      run: repositoryservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: repositoryservice
    spec:
      containers:
      - image: jorgecorral/repositoryservice:latest
        imagePullPolicy: "IfNotPresent"
        name: repositoryservice
        ports:
          - containerPort: 80        
        resources: {}      
status: {}
