apiVersion: v1
kind: Service
metadata:  
  labels:    
    run: repositoryservice
  name: repositoryservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: repositoryservice
  type: NodePort
